/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:a7b12320-5b0a-494e-a61d-d1fe44218f5f",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_ftcSwqfU0",
    "aws_user_pools_web_client_id": "39siq17b4dcmde1d7g38rroqmu",
    "oauth": {},
    "aws_user_files_s3_bucket": "sign-videos61812-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "predictions": {
        "convert": {
            "transcription": {
                "region": "eu-west-1",
                "proxy": false,
                "defaults": {
                    "language": "en-GB"
                }
            },
            "speechGenerator": {
                "region": "eu-west-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Amy",
                    "LanguageCode": "en-GB"
                }
            }
        },
        "interpret": {
            "interpretText": {
                "region": "eu-west-1",
                "proxy": false,
                "defaults": {
                    "type": "SENTIMENT"
                }
            }
        }
    }
};


export default awsmobile;
